NCC-112 Mixed Paper tests are showing the max amount of sample questi…
oat-sa/extension-tao-qtiprint pull request #64
Opened 2020-02-07 08:45 UTC by narekxxxxx

Related to task: https://oat-sa.atlassian.net/browse/NCC-112

Description: Mixed Paper tests are showing the max amount of sample questions, not the set amount

Requires: https://github.com/oat-sa/extension-tao-booklet/pull/93

How to test: Steps to help reviewers to test the behavior

Steps to reproduce: Steps to reproduce the behavior/bug

2020-02-07 13:44 UTC, ricproenca-tao requested changes
Can you please update the Updater script in `/scripts/update/Updater.php`

2020-02-10 10:22 UTC, alexeyvy commented on scripts/update/Updater.php
> +        $this->skip('1.8.3', '1.9.0');
no need for 1 more skip(), please use the one above 

        $this->skip('1.4.0', '1.9.0');

2020-02-14 09:06 UTC, alexeyvy approved these changes

2020-02-17 07:55 UTC, tikhanovichA approved these changes
Code looks good

2020-02-19 15:10 UTC, AndreyNegrov approved these changes
Good job!
[ ] New code is covered by tests (if applicable)
[ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
[x] New code is respecting code style rules
[x] New code is respecting best practices
[x] New code is not subject to concurrency issues (if applicable)
[x] The feature is working correctly on my local machine (if applicable)
[x] Acceptance criteria are respected
[x] Pull request title and description are meaningful

2020-02-19 15:48 UTC, ricproenca-tao approved these changes

2020-02-20 08:28 UTC, AndreyNegrov commented
This PR was successfully merged to develop branch but for some reason github doesn't see it.
The develop branch contains all the commits from this pr. For this reason I close this commit manually

2020-02-20 08:28 UTC, closed without merging